-- Batch: 46 D2C & consumer brands from imported sheet (deduped, Sep 2026).
-- Run once in the SQL Editor. Safe to re-run: inserts skip existing slugs.

insert into public.listings
  (slug, name, type, tagline, description, website, city, state, sector, industry, stage, founded, founders, investors, funding, lat, lng, timing, status)
values
('tanzimo', 'Tanzimo', 'startup', 'D2C / Modern Home & Lifestyle.', '', 'https://tanzimo.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Modern Home & Lifestyle', 'Bootstrapped', '2022', '', '', '', 12.92052, 77.59487, '', 'live'),
('mokobara', 'Mokobara', 'startup', 'D2C / Travel Gear & Luggage.', '', 'https://mokobara.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Travel Gear & Luggage', 'Series B', '2020', '', '', '', 13.00862, 77.6441, '', 'live'),
('dailyobjects', 'DailyObjects', 'startup', 'D2C / Lifestyle Accessories & Tech Organizers.', '', 'https://dailyobjects.com', 'Gurugram', 'Haryana', 'D2C & Consumer', 'D2C / Lifestyle Accessories & Tech Organizers', 'Series A', '2012', '', '', '', 28.41516, 77.0285, '', 'live'),
('artment', 'Artment', 'startup', 'D2C / Home Decor & Diningware.', '', 'https://theartment.com', 'Gurugram', 'Haryana', 'D2C & Consumer', 'D2C / Home Decor & Diningware', 'Bootstrapped', '2019', '', '', '', 28.43474, 77.07119, '', 'live'),
('fanzart', 'Fanzart', 'startup', 'D2C / Luxury Home Appliances.', '', 'https://fanzartfans.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Luxury Home Appliances', 'Bootstrapped', '2012', '', '', '', 12.92679, 77.64678, '', 'live'),
('wakefit', 'Wakefit', 'startup', 'D2C / Sleep & Home Solutions.', '', 'https://wakefit.co', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Sleep & Home Solutions', 'Series C+', '2016', '', '', '', 12.9218, 77.61291, '', 'live'),
('the-sleep-company', 'The Sleep Company', 'startup', 'D2C / SmartGRID Mattresses & Chairs.', '', 'https://thesleepcompany.in', 'Mumbai', 'Maharashtra', 'D2C & Consumer', 'D2C / SmartGRID Mattresses & Chairs', 'Series C+', '2019', '', '', '', 19.04468, 72.86327, '', 'live'),
('chumbak', 'Chumbak', 'startup', 'D2C / Lifestyle, Apparel & Home.', '', 'https://chumbak.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Lifestyle, Apparel & Home', 'Acquired', '2010', '', '', '', 12.95224, 77.62443, '', 'live'),
('ellementry', 'Ellementry', 'startup', 'D2C / Handcrafted Living & Kitchenware.', '', 'https://ellementry.com', 'Jaipur', 'Rajasthan', 'D2C & Consumer', 'D2C / Handcrafted Living & Kitchenware', 'Bootstrapped', '2018', '', '', '', 26.92275, 75.79961, '', 'live'),
('zingavita', 'Zingavita', 'startup', 'D2C / Health & Wellness Supplements.', '', 'https://zingavita.com', 'Gurugram', 'Haryana', 'Healthtech', 'D2C / Health & Wellness Supplements', 'Series A', '2020', '', '', '', 28.48404, 77.06205, '', 'live'),
('phool-co', 'Phool.co', 'startup', 'D2C / Sustainable Home Fragrance & Wellness.', '', 'https://phool.co', 'Kanpur', 'Uttar Pradesh', 'D2C & Consumer', 'D2C / Sustainable Home Fragrance & Wellness', 'Series A', '2017', '', '', '', 26.40363, 80.27849, '', 'live'),
('kimirica', 'Kimirica', 'startup', 'D2C / Luxury Personal Care & Bathware.', '', 'https://kimirica.com', 'Indore', 'Madhya Pradesh', 'D2C & Consumer', 'D2C / Luxury Personal Care & Bathware', 'Bootstrapped', '2012', '', '', '', 22.70836, 75.84306, '', 'live'),
('modernquests', 'Modernquests', 'startup', 'D2C / Premium Home & Office Accessories.', '', 'https://modernquests.com', 'Delhi', 'Delhi NCR', 'D2C & Consumer', 'D2C / Premium Home & Office Accessories', 'Bootstrapped', '2019', '', '', '', 28.58471, 77.21652, '', 'live'),
('varee', 'Varee', 'startup', 'D2C / Home Furnishings & Living.', '', 'https://varee.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Home Furnishings & Living', 'Series A', '2022', '', '', '', 12.92729, 77.64561, '', 'live'),
('vahdam-india', 'Vahdam India', 'startup', 'D2C / Wellness Teas & Spices.', '', 'https://vahdam.com', 'Delhi', 'Delhi NCR', 'Foodtech', 'D2C / Wellness Teas & Spices', 'Series C+', '2015', '', '', '', 28.59366, 77.21168, '', 'live'),
('sleepyhead', 'Sleepyhead', 'startup', 'D2C / Home Decor, Furniture & Bedding.', '', 'https://mysleepyhead.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Home Decor, Furniture & Bedding', 'Series A', '2017', '', '', '', 13.02626, 77.58839, '', 'live'),
('the-white-teak-company', 'The White Teak Company', 'startup', 'D2C / Decorative & Architectural Lighting.', '', 'https://whiteteak.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Decorative & Architectural Lighting', 'Acquired', '2016', '', '', '', 13.0031, 77.64071, '', 'live'),
('urban-space', 'Urban Space', 'startup', 'D2C / Home Textiles & Furnishings.', '', 'https://urbanspace.in', 'Ahmedabad', 'Gujarat', 'D2C & Consumer', 'D2C / Home Textiles & Furnishings', 'Bootstrapped', '2018', '', '', '', 23.01494, 72.62548, '', 'live'),
('pure-home-living', 'Pure Home + Living', 'startup', 'D2C / Home Decor & Tableware.', '', 'https://purehomeandliving.com', 'Delhi', 'Delhi NCR', 'D2C & Consumer', 'D2C / Home Decor & Tableware', 'Bootstrapped', '2011', '', '', '', 28.59813, 77.1865, '', 'live'),
('headway-2', 'Headway', 'startup', 'D2C / Insulated Drinkware & Accessories.', '', 'https://headwaymade.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Insulated Drinkware & Accessories', 'Bootstrapped', '2021', '', '', '', 12.92706, 77.5424, '', 'live'),
('koparo-clean', 'Koparo Clean', 'startup', 'D2C / Plant-Based Home Cleaners.', '', 'https://koparoclean.com', 'Delhi', 'Delhi NCR', 'D2C & Consumer', 'D2C / Plant-Based Home Cleaners', 'Series A', '2021', '', '', '', 28.57931, 77.24263, '', 'live'),
('foxtale', 'Foxtale', 'startup', 'D2C / Skincare & Personal Care.', '', 'https://foxtale.in', 'Mumbai', 'Maharashtra', 'D2C & Consumer', 'D2C / Skincare & Personal Care', 'Series B', '2021', '', '', '', 19.0768, 72.88498, '', 'live'),
('supertails', 'Supertails', 'startup', 'D2C / Pet Care & Nutrition.', '', 'https://supertails.com', 'Bengaluru', 'Karnataka', 'Healthtech', 'D2C / Pet Care & Nutrition', 'Series B', '2021', '', '', '', 12.92829, 77.63202, '', 'live'),
('heads-up-for-tails', 'Heads Up For Tails', 'startup', 'D2C / Pet Supplies & Care.', '', 'https://headsupfortails.com', 'Gurugram', 'Haryana', 'D2C & Consumer', 'D2C / Pet Supplies & Care', 'Series A', '2008', '', '', '', 28.45156, 77.07378, '', 'live'),
('minimalist', 'Minimalist', 'startup', 'D2C / Active Skincare.', '', 'https://beminimalist.co', 'Jaipur', 'Rajasthan', 'D2C & Consumer', 'D2C / Active Skincare', 'Series A', '2020', '', '', '', 26.87062, 75.75904, '', 'live'),
('perfora', 'Perfora', 'startup', 'D2C / Oral Care & Wellness.', '', 'https://perfora.co', 'Gurugram', 'Haryana', 'D2C & Consumer', 'D2C / Oral Care & Wellness', 'Series A', '2021', '', '', '', 28.45385, 76.97379, '', 'live'),
('bare-anatomy', 'Bare Anatomy', 'startup', 'D2C / Haircare & Personal Care.', '', 'https://bareanatomy.in', 'Gurugram', 'Haryana', 'D2C & Consumer', 'D2C / Haircare & Personal Care', 'Series A', '2019', '', '', '', 28.47875, 77.01868, '', 'live'),
('plum-goodness', 'Plum Goodness', 'startup', 'D2C / Vegan Beauty & Cosmetics.', '', 'https://plumgoodness.com', 'Thane', 'Maharashtra', 'D2C & Consumer', 'D2C / Vegan Beauty & Cosmetics', 'Series C+', '2013', '', '', '', 19.24418, 72.93421, '', 'live'),
('asaya', 'Asaya', 'startup', 'D2C / Melanin-Rich Skincare.', '', 'https://asayabeauty.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Melanin-Rich Skincare', 'Seed', '2023', '', '', '', 12.94708, 77.55575, '', 'live'),
('arata', 'Arata', 'startup', 'D2C / Clean Body & Haircare.', '', 'https://arata.in', 'Delhi', 'Delhi NCR', 'D2C & Consumer', 'D2C / Clean Body & Haircare', 'Series A', '2017', '', '', '', 28.59824, 77.21389, '', 'live'),
('anveya-living', 'Anveya Living', 'startup', 'D2C / Essential Oils & Haircare.', '', 'https://anveya.com', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Essential Oils & Haircare', 'Bootstrapped', '2018', '', '', '', 12.91944, 77.64731, '', 'live'),
('happyheads', 'Happyheads', 'startup', 'D2C / Scalp Care & Hair Wellness.', '', 'https://happyheads.in', 'Mumbai', 'Maharashtra', 'D2C & Consumer', 'D2C / Scalp Care & Hair Wellness', 'Bootstrapped', '2020', '', '', '', 19.13094, 72.88453, '', 'live'),
('slurrp-farm', 'Slurrp Farm', 'startup', 'D2C / Healthy Kids Food & Snacks.', '', 'https://slurrpfarm.com', 'Delhi', 'Delhi NCR', 'Foodtech', 'D2C / Healthy Kids Food & Snacks', 'Series C+', '2016', '', '', '', 28.57939, 77.23604, '', 'live'),
('open-secret', 'Open Secret', 'startup', 'D2C / Healthy Confectionery.', '', 'https://opensecret.in', 'Mumbai', 'Maharashtra', 'Foodtech', 'D2C / Healthy Confectionery', 'Series B', '2019', '', '', '', 19.09554, 72.82439, '', 'live'),
('country-delight', 'Country Delight', 'startup', 'D2C / Fresh Essentials & Dairy.', '', 'https://countrydelight.in', 'Gurugram', 'Haryana', 'Foodtech', 'D2C / Fresh Essentials & Dairy', 'Series C+', '2015', '', '', '', 28.4678, 76.98647, '', 'live'),
('rage-coffee', 'Rage Coffee', 'startup', 'D2C / Specialty Coffee.', '', 'https://ragecoffee.com', 'Delhi', 'Delhi NCR', 'Foodtech', 'D2C / Specialty Coffee', 'Series A', '2018', '', '', '', 28.60049, 77.16337, '', 'live'),
('jimmy-s-cocktails', 'Jimmy''s Cocktails', 'startup', 'D2C / Non-Alcoholic Mixers.', '', 'https://jimmyscocktails.com', 'Gurugram', 'Haryana', 'Foodtech', 'D2C / Non-Alcoholic Mixers', 'Series A', '2019', '', '', '', 28.40962, 76.99969, '', 'live'),
('beyond-water', 'Beyond Water', 'startup', 'D2C / Liquid Flavor Enhancers.', '', 'https://beyondwater.in', 'Bengaluru', 'Karnataka', 'Foodtech', 'D2C / Liquid Flavor Enhancers', 'Seed', '2020', '', '', '', 12.9753, 77.56581, '', 'live'),
('beyoung', 'BeYoung', 'startup', 'D2C / Everyday Casualwear.', '', 'https://beyoung.in', 'Udaipur', 'Rajasthan', 'D2C & Consumer', 'D2C / Everyday Casualwear', 'Series A', '2017', '', '', '', 24.58091, 73.70195, '', 'live'),
('creatures-of-habit', 'Creatures Of Habit', 'startup', 'D2C / Minimalist Apparel.', '', 'https://creaturesofhabit.in', 'Noida', 'Uttar Pradesh', 'D2C & Consumer', 'D2C / Minimalist Apparel', 'Bootstrapped', '2018', '', '', '', 28.51933, 77.41336, '', 'live'),
('chappers', 'Chappers', 'startup', 'D2C / Custom Footwear.', '', 'https://chappers.in', 'Pune', 'Maharashtra', 'D2C & Consumer', 'D2C / Custom Footwear', 'Bootstrapped', '2015', '', '', '', 18.49321, 73.84665, '', 'live'),
('elitty-beauty', 'Elitty Beauty', 'startup', 'D2C / Teen Makeup & Cosmetics.', '', 'https://elittybeauty.com', 'Gurugram', 'Haryana', 'D2C & Consumer', 'D2C / Teen Makeup & Cosmetics', 'Seed', '2021', '', '', '', 28.44185, 76.97774, '', 'live'),
('curlup', 'CurlUp', 'startup', 'D2C / Curly Haircare Products.', '', 'https://curlup.in', 'Bengaluru', 'Karnataka', 'D2C & Consumer', 'D2C / Curly Haircare Products', 'Bootstrapped', '2019', '', '', '', 13.00672, 77.56114, '', 'live'),
('eze-perfumes', 'Eze Perfumes', 'startup', 'D2C / Everyday Fragrances.', '', 'https://ezeperfumes.com', 'Mumbai', 'Maharashtra', 'D2C & Consumer', 'D2C / Everyday Fragrances', 'Seed', '2022', '', '', '', 19.08019, 72.89999, '', 'live'),
('wellbeing-nutrition', 'Wellbeing Nutrition', 'startup', 'D2C / Plant-Based Supplements.', '', 'https://wellbeingnutrition.com', 'Mumbai', 'Maharashtra', 'Healthtech', 'D2C / Plant-Based Supplements', 'Series B', '2019', '', '', '', 19.07617, 72.89233, '', 'live'),
('aachho', 'Aachho', 'startup', 'D2C / Ethnic Apparel & Fashion.', '', 'https://aachho.com', 'Jaipur', 'Rajasthan', 'D2C & Consumer', 'D2C / Ethnic Apparel & Fashion', 'Bootstrapped', '2018', '', '', '', 26.88076, 75.73725, '', 'live')
on conflict (slug) do nothing;

-- Unify sector labels: existing Consumer/D2C startups -> 'D2C & Consumer'.
update public.listings set sector = 'D2C & Consumer'
  where type = 'startup' and sector in ('Consumer', 'D2C');
