-- Corrections to eight investor records: seven checked against public sources,
-- plus JSW Ventures reclassified to the new CVC category.
-- Upsert: safe to re-run.

insert into public.listings
  (slug, name, type, tagline, description, website, city, state, sector, industry, stage, founded, founders, investors, funding, lat, lng, timing, status)
values
('titan-capital', 'Titan Capital', 'vc', 'Seed fund of Snapdeal founders Kunal Bahl and Rohit Bansal — early backer of Razorpay, OYO.', 'Founded in 2015 by the Snapdeal co-founders. Leads early rounds with cheques of roughly $300–500K and decides fast. Over 300 portfolio companies, which have produced 8 unicorns, 4 IPOs and 26 acquisitions. Supportive of tech-enabled food chains and retail innovation. Notable portfolio: Ola, Razorpay, Mamaearth, Urban Company, Chaayos.', 'https://www.titancapital.vc', 'Gurugram', 'Delhi NCR', 'Family Office', 'QSR, FoodTech, Consumer Retail', 'Pre-Seed to Seed', '2015', 'Kunal Bahl, Rohit Bansal', '', '', 28.4711, 77.0301, '', 'live'),
('jsw-ventures', 'JSW Ventures', 'vc', 'Early-stage venture arm of the JSW Group backing technology-led businesses.', '', 'https://www.jswventures.in', 'Mumbai', 'Maharashtra', 'CVC', '', '', '2016', '', '', '', 19.11194, 72.92746, '', 'live'),
('sauce-vc', 'Sauce.vc', 'vc', 'Consumer Micro-VC backing qsr, cloud kitchens, f&b, retail.', 'Delhi-based consumer fund founded in 2019, entering as early as pre-seed and following on through later rounds via separate early-stage and opportunities funds. Around ₹850 crore of committed capital. Focuses on nimble F&B formats, QSR brands and direct-to-consumer food products. Typical cheque size ₹2.0–₹15.0 crore. Notable consumer portfolio: Mokobara, The Whole Truth Foods, Epigamia, XYXX, Hocco Ice Creams, Innovist.', 'https://www.sauce.vc', 'Delhi', 'Delhi NCR', 'Micro PE / VC', 'QSR, Cloud Kitchens, F&B, Retail', 'Pre-Seed to Seed', '2019', 'Manu Chandra', '', '', 28.62604, 77.20186, '', 'live'),
('gruhas', 'Gruhas', 'vc', 'Multi Family Office / VC backing retail, f&b, consumer, proptech.', 'Bengaluru investment firm co-founded in 2021 by Zerodha''s Nikhil Kamath and Abhijeet Pai of the Puzzolana Group. Invests at seed and Series A across climate tech, consumer brands, senior care, sustainability and proptech, with around 68 portfolio companies. Also runs the ₹300 crore Earth Fund with Brigade Group. Typical cheque size ₹3.0–₹20.0 crore. Notable portfolio: Licious, Epoch Elder Care.', 'https://www.gruhas.com', 'Bengaluru', 'Karnataka', 'Family Office', 'Retail, F&B, Consumer, PropTech', 'Seed to Series A', '2021', 'Nikhil Kamath, Abhijeet Pai', '', '', 12.95316, 77.64091, '', 'live'),
('anicut-capital', 'Anicut Capital', 'vc', 'Early VC & Angel Fund backing qsr, f&b, retail, dining tech.', 'Founded in Chennai in 2015. Runs a full-spectrum platform of seed equity, venture debt and private credit for profitable consumer brands and SMEs — useful to F&B and QSR formats needing working capital and capex alongside equity. Around ₹4,500 crore across debt and equity strategies. Typical cheque size ₹2.0–₹20.0 crore. Notable portfolio: Bira 91, WOW! Momo, SUGAR Cosmetics, Earth Rhythm, ShareChat.', 'https://www.anicutcapital.com', 'Chennai', 'Tamil Nadu', 'VC Funds', 'QSR, F&B, Retail, Dining Tech', 'Seed to Series A', '2015', 'Ashvin Chadha, IAS Balamurugan', '', '', 13.10776, 80.26575, '', 'live'),
('narotam-sekhsaria-family-office', 'Narotam Sekhsaria Family Office', 'vc', 'Single Family Office backing consumer retail, f&b, d2c.', 'Single family office of the Ambuja Cements co-founder, established in 2006 after the Holcim sale. Over $1bn under management across public markets, commodities, private equity and real estate, with global operations. Invests directly in Indian startups and as a limited partner in domestic venture funds, favouring long-term partnerships with strong leadership teams. Typical cheque size ₹5.0–₹20.0 crore.', 'https://www.nsfo.in', 'Mumbai', 'Maharashtra', 'Family Office', 'Consumer Retail, F&B, D2C', 'Seed to Series A', '2006', 'Pulkit Sekhsaria, Padmini Somani', '', '', 19.04867, 72.92621, '', 'live'),
('patni-financial-advisors-pfa', 'Patni Financial Advisors (PFA)', 'vc', 'Single Family Office backing consumer brands, foodtech, retail.', 'Mumbai single family office of the Patni Computer Systems family, founded in 2005 and active in venture investing after the 2011 sale of the business. Deploys across listed securities, private equity, debt, real estate and other alternatives in India and internationally, with retail, software, media and healthcare technology the largest private allocations. Typical cheque size ₹2.0–₹15.0 crore. Notable portfolio: Innoviti, FAE Beauty, Bombay Shaving Company.', 'https://www.patnifa.com', 'Mumbai', 'Maharashtra', 'Family Office', 'Consumer Brands, FoodTech, Retail', 'Seed to Pre-Series A', '2005', 'Arihant Patni', '', '', 19.05908, 72.92153, '', 'live'),
('catamaran-ventures', 'Catamaran Ventures', 'vc', 'Single Family Office backing consumer retail, f&b, supply chain.', 'N.R. Narayana Murthy''s family office, established in Bengaluru in 2009. Invests across public equity, private equity and growth-stage venture capital, with a stated focus on growth capital for Indian manufacturing. Backs scalable consumer and retail models with disciplined operations and strong governance. Around 49 portfolio companies. Typical cheque size ₹5.0–₹20.0 crore. Notable consumer portfolio: Paper Boat (Hector Beverages), Cloudtail.', 'https://catamaran.in', 'Bengaluru', 'Karnataka', 'Family Office', 'Consumer Retail, F&B, Supply Chain', 'Seed to Series A', '2009', 'Deepak Padaki (President), N.R. Narayana Murthy (Chairman Emeritus)', '', '', 13.02013, 77.63688, '', 'live')
on conflict (slug) do update set name = excluded.name, type = excluded.type, tagline = excluded.tagline, description = excluded.description, website = excluded.website, city = excluded.city, state = excluded.state, sector = excluded.sector, industry = excluded.industry, stage = excluded.stage, founded = excluded.founded, founders = excluded.founders, investors = excluded.investors, funding = excluded.funding, lat = excluded.lat, lng = excluded.lng, timing = excluded.timing, status = 'live';
