-- Batch: reconciliation of the 'startup_login.xlsx' sheet against the directory (Sep 2026).
-- Adds 30 startups (incl. 1 D2C brand), 9 incubators and 39 event brands
-- that were not yet listed. Run once in the SQL Editor. Safe to re-run: inserts skip existing slugs.

-- Startups (30)
insert into public.listings
  (slug, name, type, tagline, description, website, city, state, sector, industry, stage, founded, founders, investors, funding, lat, lng, timing, status)
values
('spinny', 'Spinny', 'startup', 'Full-stack used-car platform selling certified, home-delivered cars with a money-back guarantee.', '', 'https://spinny.com', 'Gurugram', 'Haryana', 'E-commerce', 'AutoTech / Used Cars Marketplace', 'Series C+', '2015', '', '', '', 28.40474, 77.05976, '', 'live'),
('mobikwik', 'MobiKwik', 'startup', 'Digital wallet, payments and consumer-lending platform, listed on the stock exchanges in 2024.', '', 'https://mobikwik.com', 'Gurugram', 'Haryana', 'Fintech', 'FinTech / Digital Wallet & Lending', 'Public', '2009', '', '', '', 28.50648, 76.9753, '', 'live'),
('shiprocket', 'Shiprocket', 'startup', 'Shipping and fulfilment aggregator that lets D2C and e-commerce sellers ship through 25+ couriers.', '', 'https://shiprocket.in', 'Gurugram', 'Haryana', 'Logistics', 'Logistics SaaS / E-commerce Enablement', 'Series C+', '2017', '', '', '', 28.50163, 76.98071, '', 'live'),
('eruditus', 'Eruditus', 'startup', 'Executive education platform (Emeritus) delivering courses with top global universities.', '', 'https://eruditus.com', 'Mumbai', 'Maharashtra', 'Edtech', 'EdTech / Higher Executive Education', 'Series C+', '2010', '', '', '', 19.11178, 72.87498, '', 'live'),
('classplus', 'Classplus', 'startup', 'Mobile SaaS that lets educators launch their own branded app to teach and sell courses.', '', 'https://classplusapp.com', 'Noida', 'Delhi NCR', 'Edtech', 'EdTech / Educator Mobile SaaS', 'Series C+', '2018', '', '', '', 28.54894, 77.3864, '', 'live'),
('jar', 'Jar', 'startup', 'Automated micro-savings app that rounds up daily spends into digital gold and investments.', '', 'https://myjar.app', 'Bengaluru', 'Karnataka', 'Fintech', 'FinTech / Savings & Investments', 'Series B', '2021', '', '', '', 12.92283, 77.61378, '', 'live'),
('jupiter', 'Jupiter', 'startup', 'Neobank app with savings, spend insights and rewards on a partner-bank account.', '', 'https://jupiter.money', 'Bengaluru', 'Karnataka', 'Fintech', 'FinTech / Neobanking Platform', 'Series C+', '2019', '', '', '', 12.98224, 77.5988, '', 'live'),
('fi-money', 'Fi Money', 'startup', 'Neobanking and wealth app for salaried professionals: savings, investing and credit in one place.', '', 'https://fi.money', 'Bengaluru', 'Karnataka', 'Fintech', 'FinTech / Neo-banking & Wealth', 'Series C+', '2019', '', '', '', 13.02383, 77.63668, '', 'live'),
('lead-school', 'Lead School', 'startup', 'Integrated K-12 school platform bringing curriculum, tech and teacher training to affordable private schools.', '', 'https://leadschool.in', 'Mumbai', 'Maharashtra', 'Edtech', 'EdTech / K-12 School Tech Platform', 'Series C+', '2012', '', '', '', 19.02844, 72.83356, '', 'live'),
('waycool', 'WayCool', 'startup', 'Farm-to-fork food supply chain sourcing directly from farmers for retailers, restaurants and brands.', '', 'https://waycool.in', 'Chennai', 'Tamil Nadu', 'Agritech', 'AgriTech / Food Supply & Processing', 'Series C+', '2015', '', '', '', 13.03993, 80.28217, '', 'live'),
('stanza-living', 'Stanza Living', 'startup', 'Managed co-living and student housing operator across Indian cities.', '', 'https://stanzaliving.com', 'Delhi', 'Delhi NCR', 'Proptech', 'PropTech / Co-living Infrastructure', 'Series C+', '2017', '', '', '', 28.61369, 77.21532, '', 'live'),
('grip-invest', 'Grip Invest', 'startup', 'Alternative fixed-income investment platform offering bonds, SDIs and leasing deals to retail investors.', '', 'https://gripinvest.in', 'Gurugram', 'Haryana', 'Fintech', 'FinTech / Alternative Investment Platform', 'Series A', '2020', '', '', '', 28.51037, 76.97314, '', 'live'),
('insurancedekho', 'InsuranceDekho', 'startup', 'Online insurance aggregator distributing motor, health and life policies through a large agent network.', '', 'https://insurancedekho.com', 'Gurugram', 'Haryana', 'Fintech', 'InsurTech / Insurance Aggregator', 'Series B', '2016', '', '', '', 28.40781, 76.99103, '', 'live'),
('bizztm', 'BizzTM', 'startup', 'Rural social-commerce network that turns small-town retailers into service and product touchpoints.', '', 'https://bizztm.com', 'Gurugram', 'Haryana', 'E-commerce', 'RetailTech / Rural Social Commerce', 'Seed', '2020', '', '', '', 28.44804, 77.01708, '', 'live'),
('locus-sh', 'Locus.sh', 'startup', 'AI-powered logistics platform for route optimisation, dispatch and last-mile delivery.', '', 'https://locus.sh', 'Bengaluru', 'Karnataka', 'Logistics', 'Supply Chain SaaS / Logistics AI', 'Series C+', '2015', '', '', '', 12.98552, 77.62601, '', 'live'),
('dunzo', 'Dunzo', 'startup', 'Hyperlocal delivery and quick-commerce app for groceries, essentials and errands.', '', 'https://dunzo.com', 'Bengaluru', 'Karnataka', 'E-commerce', 'Hyperlocal Delivery & Quick Commerce', 'Series C+', '2014', '', '', '', 12.9293, 77.60023, '', 'live'),
('ather-energy', 'Ather Energy', 'startup', 'Electric two-wheeler maker behind the 450 series and Rizta, with its own fast-charging network; listed in 2025.', '', 'https://atherenergy.com', 'Bengaluru', 'Karnataka', 'Cleantech', 'EV / Electric Two-Wheeler Hardware', 'Public', '2013', '', '', '', 12.97063, 77.54933, '', 'live'),
('urban-company', 'Urban Company', 'startup', 'Home services marketplace for beauty, cleaning, repairs and more; listed in 2025.', '', 'https://urbancompany.com', 'Gurugram', 'Haryana', 'D2C & Consumer', 'Consumer Services / Home Services Platform', 'Public', '2014', '', '', '', 28.46299, 76.9969, '', 'live'),
('perfios', 'Perfios', 'startup', 'B2B credit-decisioning and financial-data analytics platform used by banks, NBFCs and fintechs.', '', 'https://perfios.com', 'Bengaluru', 'Karnataka', 'Fintech', 'FinTech / B2B Credit Infrastructure SaaS', 'Series C+', '2008', '', '', '', 12.92323, 77.60771, '', 'live'),
('licious', 'Licious', 'startup', 'D2C fresh meat and seafood brand with its own cold chain and same-day delivery.', '', 'https://licious.in', 'Bengaluru', 'Karnataka', 'Foodtech', 'D2C / Fresh Meat & Seafood', 'Series C+', '2015', '', '', '', 12.93126, 77.56753, '', 'live'),
('deskera', 'Deskera', 'startup', 'Cloud ERP, accounting and payroll software for small and mid-sized businesses.', '', 'https://deskera.com', 'Pune', 'Maharashtra', 'SaaS', 'Enterprise SaaS / Accounting & ERP', 'Bootstrapped', '2008', '', '', '', 18.5743, 73.88268, '', 'live'),
('ultrahuman', 'Ultrahuman', 'startup', 'Smart ring and wearables that track sleep, recovery, movement and metabolic health.', '', 'https://ultrahuman.com', 'Bengaluru', 'Karnataka', 'Healthtech', 'HealthTech / Wearables & Biomarkers', 'Series B', '2019', '', '', '', 12.97787, 77.64354, '', 'live'),
('greyorange', 'GreyOrange', 'startup', 'Warehouse robotics and AI-driven fulfilment automation for retailers and logistics providers.', '', 'https://greyorange.com', 'Gurugram', 'Haryana', 'Deeptech', 'DeepTech / Warehouse Automation & Robotics', 'Series C+', '2011', '', '', '', 28.48643, 77.07838, '', 'live'),
('loco', 'Loco', 'startup', 'Game streaming and esports platform for Indian gamers and creators.', '', 'https://getloco.org', 'Mumbai', 'Maharashtra', 'Gaming', 'Gaming / Game Streaming & Esports', 'Series A', '2018', '', '', '', 19.06108, 72.91364, '', 'live'),
('sprinto', 'Sprinto', 'startup', 'Compliance automation platform for SOC 2, ISO 27001, GDPR and other security standards.', '', 'https://sprinto.com', 'Bengaluru', 'Karnataka', 'Cybersecurity', 'Enterprise SaaS / Information Security & SOC2', 'Series B', '2020', '', '', '', 12.99632, 77.59148, '', 'live'),
('securonix', 'Securonix', 'startup', 'Cloud-native SIEM and security analytics platform with a major engineering base in Bengaluru.', '', 'https://securonix.com', 'Bengaluru', 'Karnataka', 'Cybersecurity', 'Cybersecurity / Next-Gen SIEM & Threat AI', 'Series C+', '2008', '', '', '', 12.91997, 77.60785, '', 'live'),
('invideo', 'InVideo', 'startup', 'AI video creation and editing platform used by creators and marketers worldwide.', '', 'https://invideo.io', 'Mumbai', 'Maharashtra', 'AI', 'MediaTech / AI Video Creation SaaS', 'Series A', '2017', '', '', '', 19.08482, 72.90308, '', 'live'),
('plum-benefits', 'Plum Benefits', 'startup', 'Group health insurance and employee-benefits platform for startups and SMEs.', '', 'https://plumhq.com', 'Bengaluru', 'Karnataka', 'Fintech', 'InsurTech / Employee Health Benefits', 'Series A', '2019', '', '', '', 12.93514, 77.60434, '', 'live'),
('cvent-india', 'Cvent India', 'startup', 'Event management and hospitality software; Gurugram hosts one of Cvent''s largest global offices.', '', 'https://cvent.com', 'Gurugram', 'Haryana', 'SaaS', 'Enterprise SaaS / Event Management Tech', 'Acquired', '2004', '', '', '', 28.42977, 76.97243, '', 'live'),
('mysleepwell', 'MySleepwell', 'startup', 'Direct-to-consumer store for Sleepwell mattresses and sleep-comfort products from Sheela Foam.', '', 'https://sleepwell.com', 'Noida', 'Delhi NCR', 'D2C & Consumer', 'D2C / Sleep & Home Comfort', 'Series C+', '2020', '', '', '', 28.55218, 77.39599, '', 'live')
on conflict (slug) do nothing;

-- Incubators & accelerators (9)
insert into public.listings
  (slug, name, type, tagline, description, website, city, state, sector, industry, stage, founded, founders, investors, funding, lat, lng, timing, status)
values
('aic-pondicherry-engineering-college', 'AIC-Pondicherry Engineering College', 'incubator', 'Atal Incubation Centre — NITI Aayog / PEC.', '', 'https://pec.edu/aic', 'Puducherry', 'Puducherry', 'Incubator', 'Atal Incubation Centre', '', '2018', '', '', '', 11.91897, 79.7656, '', 'live'),
('aic-great-lakes', 'AIC-Great Lakes', 'incubator', 'Atal Incubation Centre — NITI Aayog / Great Lakes Institute.', '', 'https://greatlakes.edu.in/aic', 'Chennai', 'Tamil Nadu', 'Incubator', 'Atal Incubation Centre', '', '2020', '', '', '', 13.13732, 80.30558, '', 'live'),
('iit-ropar-technology-business-incubator', 'IIT Ropar Technology Business Incubator', 'incubator', 'DeepTech Incubator — IIT Ropar / DST & MeitY.', '', 'https://tbi.iitrpr.ac.in', 'Rupnagar', 'Punjab', 'Incubator', 'DeepTech Incubator', '', '2019', '', '', '', 30.96243, 76.50273, '', 'live'),
('aic-banasthali', 'AIC-Banasthali', 'incubator', 'Atal Incubation Centre — NITI Aayog / Women-led Tech Startups.', '', 'https://aicbanasthali.org', 'Banasthali', 'Rajasthan', 'Incubator', 'Atal Incubation Centre', '', '2017', '', '', '', 26.45448, 75.85451, '', 'live'),
('aic-aureole', 'AIC-Aureole', 'incubator', 'Atal Incubation Centre — NITI Aayog / IT & Regional Innovation.', '', 'https://aureole.in', 'Gwalior', 'Madhya Pradesh', 'Incubator', 'Atal Incubation Centre', '', '2018', '', '', '', 26.21962, 78.17877, '', 'live'),
('aic-niti-assam', 'AIC-NITI Assam', 'incubator', 'Regional TBI — NITI Aayog / North-East Enterprise.', '', 'https://aicasam.org', 'Guwahati', 'Assam', 'Incubator', 'Regional TBI', '', '2021', '', '', '', 26.19549, 91.74676, '', 'live'),
('aic-preethi', 'AIC-Preethi', 'incubator', 'Atal Incubation Centre — NITI Aayog / Hardware & IoT.', '', 'https://aicpreethi.com', 'Madurai', 'Tamil Nadu', 'Incubator', 'Atal Incubation Centre', '', '2019', '', '', '', 9.90899, 78.12076, '', 'live'),
('aic-nift-delhi', 'AIC-NIFT Delhi', 'incubator', 'Sectoral Incubator — NITI Aayog / Fashion & Design Tech.', '', 'https://nift.ac.in', 'Delhi', 'Delhi NCR', 'Incubator', 'Sectoral Incubator', '', '2020', '', '', '', 28.56514, 77.23324, '', 'live'),
('iit-indore-disi', 'IIT Indore DISI', 'incubator', 'DeepTech & CPS Hub — IIT Indore / DST.', '', 'https://iiti.ac.in', 'Indore', 'Madhya Pradesh', 'Incubator', 'DeepTech & CPS Hub', '', '2020', '', '', '', 22.68981, 75.84985, '', 'live')
on conflict (slug) do nothing;

-- Event brands (39)
insert into public.listings
  (slug, name, type, tagline, description, website, city, state, sector, industry, stage, founded, founders, investors, funding, lat, lng, timing, status)
values
('build-for-india-ai-hackathon', 'Build for India AI Hackathon', 'event', 'Hackathon & Expo — Generative AI & Open Source.', '', 'https://buildforindia.ai', 'Bengaluru', 'Karnataka', 'Meetup', '', '', '2023', '', '', '', null, null, '', 'live'),
('global-ai-conclave', 'Global AI Conclave', 'event', 'Flagship Summit — Enterprise AI Adoption & Governance.', '', 'https://moneycontrol.com/mspecials/global-ai-conclave', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2023', '', '', '', null, null, '', 'live'),
('startup-tamil-nadu-conclave', 'Startup Tamil Nadu Conclave', 'event', 'State Convention — Govt of TN / Regional Entrepreneurship.', '', 'https://startuptn.in', 'Chennai', 'Tamil Nadu', 'Conference', '', '', '2022', '', '', '', null, null, '', 'live'),
('devrel-asia-conclave', 'DevRel Asia Conclave', 'event', 'Technical Summit — Developer Ecosystems & Open Source.', '', 'https://devrel.asia', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2022', '', '', '', null, null, '', 'live'),
('india-deeptech-summit', 'India DeepTech Summit', 'event', 'Sector Conclave — Semiconductors, Quantum & SpaceTech.', '', 'https://indiadeeptech.org', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2021', '', '', '', null, null, '', 'live'),
('fintech-festival-india', 'Fintech Festival India', 'event', 'Trade Expo & Conference — InsurTech, WealthTech & Banking AI.', '', 'https://fintechfestival.in', 'Delhi', 'Delhi NCR', 'Expo', '', '', '2021', '', '', '', null, null, '', 'live'),
('reinvent-retail-expo', 'ReInvent Retail Expo', 'event', 'Industry Summit — D2C Brands, E-commerce & Supply Chain.', '', 'https://reinventretail.in', 'Mumbai', 'Maharashtra', 'Summit', '', '', '2022', '', '', '', null, null, '', 'live'),
('tiecon-pune', 'TiEcon Pune', 'event', 'Regional Conclave — AutoTech, Industrial IoT & SaaS.', '', 'https://tieconpune.org', 'Pune', 'Maharashtra', 'Summit', '', '', '2011', '', '', '', null, null, '', 'live'),
('tiecon-ahmedabad', 'TiEcon Ahmedabad', 'event', 'Regional Conclave — Chemicals, D2C & Family Business Tech.', '', 'https://tieconahmedabad.org', 'Ahmedabad', 'Gujarat', 'Summit', '', '', '2013', '', '', '', null, null, '', 'live'),
('india-gaming-conclave', 'India Gaming Conclave', 'event', 'Industry Summit — Web3 Gaming, Esports & Game Dev.', '', 'https://indiagamingconclave.com', 'Delhi', 'Delhi NCR', 'Summit', '', '', '2021', '', '', '', null, null, '', 'live'),
('dpiit-startup-awards-showcase', 'DPIIT Startup Awards Showcase', 'event', 'National Award Ceremony — Government Recognition & Scaling.', '', 'https://startupindia.gov.in', 'Delhi', 'Delhi NCR', 'Awards', '', '', '2020', '', '', '', null, null, '', 'live'),
('cleantech-horizon-india', 'CleanTech Horizon India', 'event', 'Sector Summit — Hydrogen Energy, Batteries & Carbon Tech.', '', 'https://cleantechhorizon.in', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2022', '', '', '', null, null, '', 'live'),
('genai-summit-india', 'GenAI Summit India', 'event', 'Specialized Summit — LLM Infrastructure & AI Enterprise.', '', 'https://genaisummit.in', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2023', '', '', '', null, null, '', 'live'),
('gift-city-fintech-conclave', 'GIFT City Fintech Conclave', 'event', 'International Financial Summit — Cross-border Finance & Web3.', '', 'https://giftgujarat.in', 'Gandhinagar', 'Gujarat', 'Summit', '', '', '2022', '', '', '', null, null, '', 'live'),
('agritech-india-summit', 'Agritech India Summit', 'event', 'Sector Conclave — Ag-Fintech, Supply Chain & IoT.', '', 'https://agritechindiasummit.in', 'Delhi', 'Delhi NCR', 'Summit', '', '', '2020', '', '', '', null, null, '', 'live'),
('women-founders-conclave', 'Women Founders Conclave', 'event', 'Focus Summit — Diversity in Tech & VC Access.', '', 'https://womenfounderssummit.in', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2021', '', '', '', null, null, '', 'live'),
('design360-tech-summit', 'Design360 Tech Summit', 'event', 'UX & Tech Conference — Product Design & Consumer Tech UI.', '', 'https://design360.in', 'Mumbai', 'Maharashtra', 'Conference', '', '', '2022', '', '', '', null, null, '', 'live'),
('web3-startup-india-meet', 'Web3 Startup India Meet', 'event', 'Developer Summit — Blockchain, DeFi & Open Protocol.', '', 'https://web3india.org', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2022', '', '', '', null, null, '', 'live'),
('e-summit-iit-delhi', 'E-SUMMIT IIT Delhi', 'event', 'Academic Summit — DeepTech, CleanTech & Innovation.', '', 'https://edc-iitd.org', 'Delhi', 'Delhi NCR', 'Summit', '', '', '2007', '', '', '', null, null, '', 'live'),
('e-summit-iit-madras', 'E-SUMMIT IIT Madras', 'event', 'Academic Summit — Engineering Hardware & R&D.', '', 'https://cefiitmadras.org', 'Chennai', 'Tamil Nadu', 'Summit', '', '', '2006', '', '', '', null, null, '', 'live'),
('gtr-india-global-trade-review', 'GTR India (Global Trade Review)', 'event', 'Trade Finance Summit — Supply Chain Finance & FinTech.', '', 'https://gtreview.com', 'Mumbai', 'Maharashtra', 'Expo', '', '', '2013', '', '', '', null, null, '', 'live'),
('superai-india-conclave', 'SuperAI India Conclave', 'event', 'AI Flagship Summit — Generative AI Infrastructure & Enterprise.', '', 'https://superai.in', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2023', '', '', '', null, null, '', 'live'),
('india-saas-leadership-summit', 'India SaaS Leadership Summit', 'event', 'Founder Retreat — Cross-Border SaaS Scaling & PLG.', '', 'https://saasleadership.in', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2021', '', '', '', null, null, '', 'live'),
('semicon-india', 'SemiCon India', 'event', 'Government Trade Expo — Semiconductor Ecosystem & Hardware.', '', 'https://semiconindia.org', 'Gandhinagar', 'Gujarat', 'Expo', '', '', '2022', '', '', '', null, null, '', 'live'),
('startup-odisha-conclave', 'Startup Odisha Conclave', 'event', 'State Convention — Govt of Odisha / Tier-2 Innovation.', '', 'https://startupodisha.gov.in', 'Bhubaneswar', 'Odisha', 'Conference', '', '', '2021', '', '', '', null, null, '', 'live'),
('e-summit-iit-kharagpur', 'E-SUMMIT IIT Kharagpur', 'event', 'Academic Summit — DeepTech, AgriTech & Student Ventures.', '', 'https://ecell-iitkgp.org', 'Kharagpur', 'West Bengal', 'Summit', '', '', '2006', '', '', '', null, null, '', 'live'),
('india-ev-conclave', 'India EV Conclave', 'event', 'Industry Summit — Battery Tech, Charging Infrastructure & Fleet.', '', 'https://indiaevconclave.com', 'Delhi', 'Delhi NCR', 'Summit', '', '', '2021', '', '', '', null, null, '', 'live'),
('devops-india-summit', 'DevOps India Summit', 'event', 'Technical Summit — Cloud Native, SRE & Platform Engineering.', '', 'https://devopsindiasummit.com', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2018', '', '', '', null, null, '', 'live'),
('adtech-india-conclave', 'AdTech India Conclave', 'event', 'Industry Summit — Programmatic Media, MarTech & D2C Analytics.', '', 'https://adtechindia.in', 'Mumbai', 'Maharashtra', 'Summit', '', '', '2020', '', '', '', null, null, '', 'live'),
('fintech-world-forum-india', 'FinTech World Forum India', 'event', 'Trade Summit — InsurTech, WealthTech & Neobanking.', '', 'https://fintechforum.in', 'Delhi', 'Delhi NCR', 'Expo', '', '', '2022', '', '', '', null, null, '', 'live'),
('cyber-security-conclave-india', 'Cyber Security Conclave India', 'event', 'Enterprise Summit — Threat Intelligence, Zero Trust & SecOps.', '', 'https://cybersecurityconclave.in', 'Hyderabad', 'Telangana', 'Summit', '', '', '2019', '', '', '', null, null, '', 'live'),
('india-retail-tech-expo', 'India Retail Tech Expo', 'event', 'Trade Showcase — Omnichannel Retail, POS & Supply Chain.', '', 'https://retailtechexpo.in', 'Mumbai', 'Maharashtra', 'Expo', '', '', '2021', '', '', '', null, null, '', 'live'),
('clean-energy-india-expo', 'Clean Energy India Expo', 'event', 'Sector Expo — Solar, Green Hydrogen & Storage Systems.', '', 'https://cleanenergyindia.in', 'Delhi', 'Delhi NCR', 'Expo', '', '', '2020', '', '', '', null, null, '', 'live'),
('agritech-asia-conclave', 'Agritech Asia Conclave', 'event', 'Regional Summit — Precision Farming, Ag-Fintech & IoT.', '', 'https://agritechasia.in', 'Bengaluru', 'Karnataka', 'Summit', '', '', '2022', '', '', '', null, null, '', 'live'),
('b2b-saas-growth-conference', 'B2B SaaS Growth Conference', 'event', 'Specialized Forum — Go-To-Market Strategies & Sales Operations.', '', 'https://saasgrowth.in', 'Chennai', 'Tamil Nadu', 'Summit', '', '', '2022', '', '', '', null, null, '', 'live'),
('web3-builders-meetup-india', 'Web3 Builders Meetup India', 'event', 'Developer Hackathon — DeFi Protocols, Smart Contracts & dApps.', '', 'https://web3builders.in', 'Bengaluru', 'Karnataka', 'Meetup', '', '', '2023', '', '', '', null, null, '', 'live'),
('deeptech-india-investor-summit', 'DeepTech India Investor Summit', 'event', 'Investor Showcase — Spinoffs, SpaceTech & Quantum Computing.', '', 'https://deeptechinvestor.in', 'Bengaluru', 'Karnataka', 'Expo', '', '', '2022', '', '', '', null, null, '', 'live'),
('women-in-tech-india-summit', 'Women in Tech India Summit', 'event', 'Diversity Leadership Summit — Mentorship, VC Funding & STEM Career Growth.', '', 'https://womenintechindia.in', 'Gurugram', 'Haryana', 'Summit', '', '', '2021', '', '', '', null, null, '', 'live'),
('global-logistics-supply-chain-conclave', 'Global Logistics & Supply Chain Conclave', 'event', 'Industry Expo — Third-Party Logistics, Warehouse Tech & Freight.', '', 'https://supplychainconclave.in', 'Mumbai', 'Maharashtra', 'Expo', '', '', '2020', '', '', '', null, null, '', 'live')
on conflict (slug) do nothing;
