-- Trending Spacetech: 23 researched Indian spacetech startups (Aug 2026).
-- Run once in the SQL Editor. Safe to re-run: existing slugs are skipped.

insert into public.listings
  (slug, name, type, tagline, description, website, city, state, sector, industry, stage, founded, founders, investors, funding, lat, lng, timing, status)
values
('skyroot-aerospace', 'Skyroot Aerospace', 'startup', 'Builder of the Vikram launch vehicles — flew India''s first private rocket and leads the country''s spacetech funding charts.', '', 'https://skyroot.in', 'Hyderabad', 'Telangana', 'Spacetech', 'Space Technology', 'Series B', '2018', 'Pawan Kumar Chandana, Naga Bharath Daka', '', '$145M', 17.47441, 78.40289, '', 'live'),
('agnikul-cosmos', 'Agnikul Cosmos', 'startup', 'IIT Madras spinout that 3D-prints single-piece rocket engines; launched Agnibaan SOrTeD from its own private launchpad.', '', 'https://agnikul.in', 'Chennai', 'Tamil Nadu', 'Spacetech', 'Space Technology', 'Series B', '2017', 'Srinath Ravichandran, Moin SPM', '', '', 13.05192, 80.27492, '', 'live'),
('pixxel', 'Pixxel', 'startup', 'Google-backed hyperspectral imaging constellation — its Firefly satellites read Earth''s health in 250+ spectral bands.', '', 'https://www.pixxel.space', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Series B', '2019', 'Awais Ahmed, Kshitij Khandelwal', '', '', 12.94692, 77.57452, '', 'live'),
('digantara', 'Digantara', 'startup', 'Mapping everything in orbit — space situational awareness infrastructure to keep satellites safe from debris.', '', 'https://digantara.co.in', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Series A', '2018', 'Anirudh Sharma, Rahul Rawat', '', '', 12.93437, 77.60034, '', 'live'),
('dhruva-space', 'Dhruva Space', 'startup', 'Full-stack satellite platforms, deployers and ground stations; one of India''s first private space companies.', '', 'https://dhruvaspace.com', 'Hyderabad', 'Telangana', 'Spacetech', 'Space Technology', 'Series A', '2012', 'Sanjay Nekkanti', '', '', 17.43289, 78.47789, '', 'live'),
('bellatrix-aerospace', 'Bellatrix Aerospace', 'startup', 'In-space propulsion maker — Hall thrusters and green propellants powering satellite orbit transfers.', '', 'https://www.bellatrix.aero', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Series A', '2015', 'Rohan M Ganapathy, Yashas Karanam', '', '', 12.99883, 77.60428, '', 'live'),
('galaxeye', 'GalaxEye', 'startup', 'IIT Madras spinout building Drishti, the world''s first multi-sensor SAR + optical imaging satellite.', '', 'https://www.galaxeye.space', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Series A', '2021', 'Suyash Singh', '', '', 12.92662, 77.55248, '', 'live'),
('satsure', 'SatSure', 'startup', 'Satellite data analytics for agriculture, banking and climate — decision intelligence from orbit.', '', 'https://satsure.co', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Series A', '2017', 'Prateep Basu', '', '', 13.00194, 77.63574, '', 'live'),
('manastu-space', 'Manastu Space', 'startup', 'Green propulsion and in-orbit servicing tech to refuel and de-risk the satellite economy.', '', 'https://www.manastuspace.com', 'Mumbai', 'Maharashtra', 'Spacetech', 'Space Technology', 'Seed', '2017', 'Tushar Jadhav, Ashtesh Kumar', '', '', 19.03611, 72.87967, '', 'live'),
('inspecity', 'InspeCity', 'startup', 'IIT Bombay spinout building servicing vehicles for life extension and de-orbiting of satellites.', '', 'https://www.inspecity.com', 'Mumbai', 'Maharashtra', 'Spacetech', 'Space Technology', 'Seed', '2022', 'Arindrajit Chowdhury', '', '', 19.02907, 72.88303, '', 'live'),
('etherealx', 'EtherealX', 'startup', 'Developing Razor Crest Mk-1, a fully reusable medium-lift launch vehicle to crash the cost of orbit.', '', 'https://www.etherealx.space', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Seed', '2022', 'Manu J Nair, Prashanth Sharma, Shubhayu Sardar', '', '', 13.00123, 77.63201, '', 'live'),
('astrogate-labs', 'Astrogate Labs', 'startup', 'Laser-based optical communication terminals moving satellite data at fibre-like speeds.', '', 'https://astrogatelabs.com', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Seed', '2017', 'Nitish Singh', '', '', 13.0068, 77.61937, '', 'live'),
('kawa-space', 'Kawa Space', 'startup', 'Earth-observation infrastructure and APIs — satellite data as a developer product.', '', 'https://kawa.space', 'Mumbai', 'Maharashtra', 'Spacetech', 'Space Technology', 'Seed', '2019', 'Kris Nair', '', '', 19.06484, 72.93023, '', 'live'),
('skyserve', 'SkyServe', 'startup', 'Edge computing on satellites — running AI models in orbit so only insights come down.', '', 'https://skyserve.ai', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Seed', '2020', 'Vinay Simha', '', '', 12.94762, 77.61076, '', 'live'),
('piersight', 'PierSight', 'startup', 'Building a SAR satellite constellation for all-weather maritime surveillance of every ocean.', '', 'https://www.piersight.space', 'Ahmedabad', 'Gujarat', 'Spacetech', 'Space Technology', 'Seed', '2023', 'Gaurav Seth, Vinit Bansal', '', '', 22.98051, 72.60658, '', 'live'),
('xdlinx-space-labs', 'XDLINX Space Labs', 'startup', 'Designs and manufactures advanced small satellites for global commercial and defence missions.', '', 'https://xdlinx.space', 'Hyderabad', 'Telangana', 'Spacetech', 'Space Technology', 'Seed', '2022', '', '', '', 17.37726, 78.42799, '', 'live'),
('takeme2space', 'TakeMe2Space', 'startup', 'Orbital AI labs — satellites anyone can task to run experiments and models in space.', '', 'https://www.takeme2space.com', 'Hyderabad', 'Telangana', 'Spacetech', 'Space Technology', 'Pre-seed', '2023', 'Ronak Kumar Samantray', '', '', 17.38671, 78.43034, '', 'live'),
('orbitaid-aerospace', 'OrbitAID Aerospace', 'startup', 'On-orbit refueling and docking technology to keep satellites alive longer.', '', '', 'Chennai', 'Tamil Nadu', 'Spacetech', 'Space Technology', 'Pre-seed', '2021', 'Sakthikumar Rajendran', '', '', 13.095, 80.30991, '', 'live'),
('spacefields', 'SpaceFields', 'startup', 'Aerospike rocket engines and advanced solid propulsion for space and defence.', '', 'https://spacefields.in', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Pre-seed', '2022', 'Apurwa Masook', '', '', 12.95796, 77.63213, '', 'live'),
('astrome-technologies', 'Astrome Technologies', 'startup', 'Wireless backhaul from space and ground — GigaMesh millimetre-wave products connecting the unconnected.', '', 'https://astrome.co', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Series A', '2015', 'Neha Satak, Prasad Bhat', '', '', 13.02487, 77.54321, '', 'live'),
('aadyah-aerospace', 'Aadyah Aerospace', 'startup', 'Space and defence systems house building satellite subsystems, optics and precision actuators.', '', 'https://aadyah.com', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Seed', '2016', '', '', '', 12.99904, 77.60407, '', 'live'),
('kepler-aerospace', 'Kepler Aerospace', 'startup', 'Aerospace engineering firm developing mission systems and services for the new space economy.', '', 'https://www.kepleraero.com', 'Bengaluru', 'Karnataka', 'Spacetech', 'Space Technology', 'Seed', '2018', '', '', '', 13.02277, 77.56343, '', 'live'),
('vasundharaa-geo-technologies', 'Vasundharaa Geo Technologies', 'startup', 'Geospatial intelligence from satellite imagery for governance, disaster response and BFSI.', '', 'https://vasundharaa.in', 'Pune', 'Maharashtra', 'Spacetech', 'Space Technology', 'Seed', '2017', '', '', '', 18.47102, 73.8283, '', 'live')
on conflict (slug) do nothing;
